# Generated by Django 5.2.4 on 2025-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
