# Generated by Django 5.2.4 on 2025-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentpage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyVistors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notify Visitor',
                'verbose_name_plural': 'Notify Visitors',
            },
        ),
    ]
