# Generated by Django 5.2.4 on 2025-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('date_taken', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
