# Generated by Django 5.2.4 on 2025-07-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='GalleryImage',
        ),
    ]
