# Generated by Django 5.2.4 on 2025-08-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_photo_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='caption',
            new_name='title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('empowerment', 'Economic Empowerment'), ('mentorship', 'Education & Mentorship'), ('menstrual', 'Menstrual Health'), ('housing', 'Housing & Sanitation'), ('community', 'Community Events'), ('health', 'Health & Wellness')], default='community', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='date_taken',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
